### ISSUE TITLE
can't specify id_rsa to use

### ISSUE THREAD

**Issue by junyu-w** [Berkeley-CS162/vagrant#1]
I met this git issue that said

```
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

 when trying to access my private cs162 git repo within the vagrant box and I have set up a id_rsa key on the host machine. But the problem is I how two `id_rsa` in my `.ssh` dir for my two different github account. But it seems like the vagrant box didn't forward the right one. Is there a way to update the vagrant file so that we can forward a specific id_rsa key to use?

**Comment by junyu-w** [comment]
the work-around I'm using right now is manually copy my desired id_rsa and id_rsa.pub into the .ssh dir of the vagrant box

**Comment by rogerhub** [comment]
The ssh agent should forward all the keys it knows about. You may have to do `ssh-add ~/.ssh/....` before  it will work.

You can also create a new key on the VM and then add that to your GitHub account (you can have more than 1 key per GitHub account)

**Comment by junyu-w** [comment]
Thanks :+1:
