### ISSUE TITLE
Issues with Vagrant Up on Ubuntu 18.04 as host OS

### ISSUE THREAD

**Issue by njriasan** [Berkeley-CS162/vagrant#4]
I tried downloading this repo and running vagrant up. I get the following output.
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown 'enp0s8' || true
/sbin/ip addr flush dev 'enp0s8'
# Remove any previous network modifications from the interfaces file
sed -e '/^#VAGRANT-BEGIN/,$ d' /etc/network/interfaces > /tmp/vagrant-network-interfaces.pre
sed -ne '/^#VAGRANT-END/,$ p' /etc/network/interfaces | tac | sed -e '/^#VAGRANT-END/,$ d' | tac > /tmp/vagrant-network-interfaces.post

cat \
  /tmp/vagrant-network-interfaces.pre \
  /tmp/vagrant-network-entry \
  /tmp/vagrant-network-interfaces.post \
  > /etc/network/interfaces

rm -f /tmp/vagrant-network-interfaces.pre
rm -f /tmp/vagrant-network-entry
rm -f /tmp/vagrant-network-interfaces.post

/sbin/ifup 'enp0s8'

Stdout from the command:



Stderr from the command:

bash: line 5: /sbin/ifdown: No such file or directory
bash: line 21: /sbin/ifup: No such file or directory
```

To Fix:
After running `vagrant up` run
`vagrant ssh`
`sudo apt-get install ifupdown`
Reload the VM.

I do not know if we can install this beforehand to avoid this issue.

**Comment by samkumar** [comment]
Interesting. This doesn't show up for me on Ubuntu 16.04. What vagrant version do you have (in case that's relevant)?

This semester I'm distributing a box that's already built, so I wonder if that will prevent this issue from showing up. If not, I should be able to install install `ifupdown` before releasing, which should fix it.

**Comment by njriasan** [comment]
Version 2.0.1

**Comment by njriasan** [comment]
I didn't get this when following the commands in hw0.
